name: C++ CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-11 make libgtest-dev
        sudo ln -sf /usr/bin/g++-11 /usr/bin/g++

    - name: Build tests
      run: |
        make test

    - name: Execute tests
      run: |
        ./tests/test-card

    - name: Build release
      run: |
        make clean
        make

    - name: Cleanup
      run: |
        make cleanall 